#version 430

layout (local_size_x = 4, local_size_y = 4) in;

uniform uint num_sprites;

layout (std430, binding = 0) readonly buffer vert_buff_in {
    vec3 pos_in[];
};

layout (std430, binding = 0) writeonly buffer vert_buff_out {
    vec3 pos_out[];
};

void main() {
    uint vtx_id = 16 * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y;

    if (vtx_id < num_sprites) pos_out[vtx_id] = pos_in[vtx_id];
}