#version 430

#include "sprite_def.glsl"

layout (local_size_x = 4, local_size_y = 4) in;

uniform uint num_sprites;

layout (std430, binding = 0) readonly buffer sprite_buff_in {
    Sprite sprites_in[];
};

layout (std430, binding = 1) writeonly buffer sprite_buff_out {
    Sprite sprites_out[];
};

void main() {
    uint vtx_id = 16 * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y;

    if (vtx_id < num_sprites) {
        sprites_out[vtx_id].pos = sprites_in[vtx_id].pos;
        sprites_out[vtx_id].vel = sprites_in[vtx_id].vel;
    }
}