#version 430

layout (local_size_x = 4, local_size_y = 4) in;

#include "particle_def.glsl"

uniform float osg_FrameTime;

void main() {
    Cell c_a = c[gl_GlobalInvocationID.x];
    Cell c_b = c[gl_GlobalInvocationID.y];

    // calculate distance between two cells' centres of mass
    // Newton's law of gravity ( F = G m1 m2 / r**2 )
    float force_mag = G * c_a.mass * c_b.mass / dist_sq(c_b.pos - c_a.pos);
    // save force to cell
    c_a.force = vect_a_to_b * force_mag;
    c_b.force = -1. * c_a.force;
}