#version 430

layout (local_size_x = 16, local_size_y = 4) in;
uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;
uniform uint num_sprites;

struct Sprite_data {
    vec3 pos;
    float vel;
};

layout (std430, binding = 0) buffer sprite_buff {
    Sprite_data sprites[];
};

void main() {
    uint sprite_id = gl_GlobalInvocationID.x + 4 * gl_GlobalInvocationID.y;
    
    if (sprites[sprite_id].vel == 0.) {
        if ((uint(osg_FrameTime*2.)%4 == 0) 
            && (sprite_id == 2050)) {
            sprites[sprite_id].vel = .2;
        } else if ((uint(osg_FrameTime*2)%4 == 11) 
            && (sprite_id == 1050)) {
            sprites[sprite_id].vel = .2;
        } else if ((uint(osg_FrameTime*2)%4 == 6) 
            && (sprite_id == 350)) {
            sprites[sprite_id].vel = .2;
        } else if ((uint(osg_FrameTime*2)%4 == 17) 
            && (sprite_id == 1360)) {
            sprites[sprite_id].vel = .2;
        }
    }

    // spring potential f = k(u1 - u2 / ?) ??
    float force = 0.;
    if (sprite_id%160 != 0)
        force = sprites[sprite_id-1].pos.z * .2;
    if ((sprite_id+1)%160 != 0)
        force += sprites[sprite_id+1].pos.z * .2;
    sprites[sprite_id].vel -= force * osg_DeltaFrameTime * .2;
    sprites[sprite_id].pos.z += sprites[sprite_id].vel * osg_DeltaFrameTime * .1;// + sin(osg_FrameTime + sprite_id*20.)*.1;
}