#version 430

layout (local_size_x = 1, local_size_y = 4) in;
uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;

#include "hex_data.glsl"

void main() {
    uint sprite_id = gl_GlobalInvocationID.x + 64 * gl_GlobalInvocationID.y;
    vec3 force = vec3(0.);

    force.z += sprites[uint(sprites[sprite_id].neighbour.x)].pos_1.z
                    - sprites[sprite_id].pos_1.z;
    force.z += sprites[uint(sprites[sprite_id].neighbour.y)].pos_1.z
                    - sprites[sprite_id].pos_1.z;
    force.z += sprites[uint(sprites[sprite_id].neighbour.z)].pos_1.z
                    - sprites[sprite_id].pos_1.z;

    // linearly integrate force to velocity
    float dF = sprites[sprite_id].force.z - force.z;
    float dV = ((dF * dF) * (osg_DeltaFrameTime * osg_DeltaFrameTime)) / 2.;
    // integrate to position
    sprites[sprite_id].vel.z += pow(dV, max(1.,dF));
    sprites[sprite_id].pos_0.z += sprites[sprite_id].vel.z * osg_DeltaFrameTime;
}
    