#version 430

layout (local_size_x = 1, local_size_y = 4) in;
uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;

#include "hex_data.glsl"

void main() {
    uint sprite_id = gl_GlobalInvocationID.x + 64 * gl_GlobalInvocationID.y;
    sprites[sprite_id].force = vec3(0.);
    sprites[sprite_id].pos_1 = sprites[sprite_id].pos_0;

    sprites[sprite_id].force.z += (sprites[uint(sprites[sprite_id].neighbour.x)].pos_0.z
                - sprites[sprite_id].pos_0.z) * osg_DeltaFrameTime;
    sprites[sprite_id].force.z += (sprites[uint(sprites[sprite_id].neighbour.y)].pos_0.z
                - sprites[sprite_id].pos_0.z) * osg_DeltaFrameTime;
    sprites[sprite_id].force.z += (sprites[uint(sprites[sprite_id].neighbour.z)].pos_0.z
                - sprites[sprite_id].pos_0.z) * osg_DeltaFrameTime;

    float dV = sprites[sprite_id].vel.z + sprites[sprite_id].force.z;
    sprites[sprite_id].pos_1.z += dV * osg_DeltaFrameTime;
}