#version 430

layout (local_size_x = 4, local_size_y = 4) in;
uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;

#pragma include "hex_data.glsl"

void main() {
    uint sprite_id = gl_GlobalInvocationID.x + 64 * gl_GlobalInvocationID.y;

    vec3 force = vec3(0.);

    for (int nbr = 0; nbr < 3; nbr++) {
        force.z += (sprites[sprites[sprite_id].neighbour[nbr]].pos.z
                    - sprites[sprite_id].pos.z) * osg_DeltaFrameTime;
    }

    if(((int(osg_FrameTime) + sprite_id)%60)==0 
        && abs(sprites[sprite_id].pos.z) < .1
        && abs(sprites[sprite_id].vel.z) < .1) {
        force.z += sin(osg_FrameTime);
    }
    
    sprites[sprite_id].vel.z += force.z;
    sprites[sprite_id].pos.z += sprites[sprite_id].vel.z * osg_DeltaFrameTime;// + sin(osg_FrameTime + sprite_id*20.)*.1;
}