#version 430

layout (local_size_x = 4, local_size_y = 4) in;

#include "particle_def.glsl"

void main() {
    uint p_id = 16 * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y;

    uint c_id = find_cell_idx(p_id);

    // move centre of mass
    c[c_id].pos = (c[c_id].pos * c[c_id].mass + p[p_id].pos * p[p_id].mass) * .5;
    c[c_id].mass += p[p_id].mass;

    // sort particles by cell (hashmap)
    
}