#version 430

layout (local_size_x = 4, local_size_y = 4) in;

#include "simple_particle.glsl"

void main() {
    Particle p_a = p[gl_GlobalInvocationID.x];
    Particle p_b = p[(gl_GlobalInvocationID.y + gl_GlobalInvocationID.x + 1)%num_sprites];

    vec3 diff_pos = p_a.pos - p_b.pos;
    if (dist_sq(diff_pos) < .5) {
        f[half_pairs * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y] = 
            diff_pos;
    } else {
        f[half_pairs * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y] =
            diff_pos * (G * p_a.mass * p_b.mass / dist_sq(p_a.pos - p_b.pos));
    }
}