#version 430

#include "sprite_def.glsl"

layout (local_size_x = 4, local_size_y = 4) in;

//uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;
uniform uint num_sprites;

layout (std430, binding = 0) readonly buffer sprite_buff_in {
    Sprite sprites_in[];
};

layout (std430, binding = 1) buffer sprite_buff_out {
    Sprite sprites_out[];
};

layout (std430, binding = 2) buffer cell_buff {
    Cell cells[];
};

void main() {
    uint g_id = 16 * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y;
    //pos_out[vtx_id] = pos_in[vtx_id];

    Cell invcell = cells[g_id];

    for (uint oth_cell = 0; oth_cell < num_cells; oth_cell++) {
        if (oth_cell == g_id) continue;
        // TODO calculate forces between cells
        // push away when too close
        vec3 diffPos = invcell.pos - oth_cell.pos;
        if (abs(diffPos.x) < .5 && abs(diffPos.y) < .5 && abs(diffPos.z) < .5) {
            //pos_out[vtx_id] += diffPos * osg_DeltaFrameTime;
            sprites_out[vtx_id].vel += diffPos * osg_DeltaFrameTime;
        }
    }

    for (uint idx = 0; idx < invcell.num_sprites; idx++) {
        Sprite curr_spr_in = sprites_in[invcell.sprites[idx]];
        Sprite curr_spr_out = sprites_out[invcell.sprites[idx]];

        // damping factor on inertia
        curr_spr_out.vel = curr_spr_in.vel * .9;

    
        
        
    }
    // position update
    sprites_out[vtx_id].pos = sprites_in[vtx_id].pos + sprites_out[vtx_id].vel * osg_DeltaFrameTime;
}