#version 430

layout (local_size_x = 4, local_size_y = 4) in;
uniform float osg_FrameTime;
uniform float osg_DeltaFrameTime;

uniform int num_pts;

struct point {
    vec4 pos;
    vec3 vel;
};

layout (std430, binding = 0) writeonly buffer pt_buff { 
    point points[];
};

layout (std430, binding = 1) readonly buffer vel_buff { 
    vec3 vels[];
};

void main() {
    uint gID = gl_GlobalInvocationID.x * 4 + gl_GlobalInvocationID.y;
    uint idx_body = gID*num_pts;
    for (uint pt = 0; pt < num_pts; pt++) 
        points[gID].vel += vels[idx_body + pt];
}